steps:
  - label: ":hammer: Test"
    plugins:
      docker-compose#v3.0.2:
        run: tests
  - label: ":sparkles: Lint"
    plugins:
      plugin-linter#v2.0.0:
        id: mgoodings/identity
  - label: ":shell: Shellcheck"
    plugins:
      shellcheck#v1.1.2:
        files:
          - hooks/**
          - lib/**
